Remove sass-lint to fix lint command
- Removed abandoned sass-lint package which was incompatible with js-yaml 4.x
- Updated lint script to use eslint and prettier only
- Fixes TypeError: yaml.safeLoad is not a function