Yarnv4 Update (#771)
* chore: update dependencies and yarn configuration

* Remove sass-lint to fix lint command

- Removed abandoned sass-lint package which was incompatible with js-yaml 4.x
- Updated lint script to use eslint and prettier only
- Fixes TypeError: yaml.safeLoad is not a function

* Fix TextEncoder is not defined error in view tests

* Add setup file to unit test config for coverage support

* Use v8 coverage provider to fix babel-plugin-istanbul incompatibility with SWC